### ISSUE TITLE
I think Firefox 75 broke auto-hide.css

### ISSUE THREAD

**Issue by LOuroboros** [Timvde/UserChrome-Tweaks#174]
Title.
In Firefox 75, possibly a product of the Megabar, the position of the navbar is off when using [toolbars/auto-hide.css](https://github.com/Timvde/UserChrome-Tweaks/blob/master/toolbars/auto-hide.css).
https://streamable.com/tze7ej

**Comment by ameerabsalam** [comment]
Likewise here with 75 under linux

**Comment by A-Lamia** [comment]
Had the same problem, i came up with a quick fix not sure yet if there is a better way currently but it's working for now.

```css
#urlbar { 
  top: 0!important; 
  position: absolute!important;
} 

#urlbar-input-container {
  height: 100%!important;
}
```

**Comment by pauricthelodger** [comment]
Cheers for that, @A-Lamia!

With yours I got the following:

![Original](https://user-images.githubusercontent.com/41227/79337357-4369ae80-7f1d-11ea-8510-385a5c93c2f2.png)

So I tweaked it a little bit more to this:

```
#urlbar { 
  position: absolute!important;  
  top: 3px!important; 
} 

#urlbar-input-container {
  height: 26px!important;
}
```
And got:

![Tweaked](https://user-images.githubusercontent.com/41227/79337354-42388180-7f1d-11ea-8ba6-84ba02f7cc92.png)

The tweaks might just be for my local though so ymmv =)

**Comment by A-Lamia** [comment]
Glad it helped @pauricthelodger.

That's why it's a quick fix, `top` and `height` need to be adjusted to fit your local firefox version, been looking in to a more static solution but the couple i have come up with had other side effects that are not desirable.

**Comment by A-Lamia** [comment]
So after some time i have figured out that the issue is the code is setting `#urlbar`'s internal variable `--urlbar-toolbar-height` to `1px` from `32px` (or what ever yours is set to.). 

The value of `--urlbar-toolbar-height` from what i can tell (could be wrong) is fetched from what ever the height of `#nav-bar` is on startup, in this case it gets set to 1px because of auto hide.

This is causing a `calc()` function on the `top` property in `#urlbar[breakout]` to calculate incorrectly giving us the positioning errors. 

I'm not completely sure but from my local firefox this calculation error has caused a couple of bad side effects i have also fixed. `#urlbar-input-container` being sized incorrectly and the `.urlbarView` positioning overlapping with toolbar the only side effect i have yet to fix is an animation flash that happens when clicking away from the url view.

```css
#nav-bar {
        --navbar-height: 32px;
        --urlbar-height: 26px;
 }

 #nav-bar:not([customizing="true"]):not([inFullscreen]){
	min-height: 1px !important;
	max-height: 0px !important;
	margin-top: 1px !important;
  	margin-bottom: -1px !important;
	transition: all 50ms linear 0s !important;
	z-index: -5 !important;
}

#navigator-toolbox:hover:not([inFullscreen]) :-moz-any(#nav-bar),
#navigator-toolbox:focus-within :-moz-any(#nav-bar) {
        min-height: var(--navbar-height) !important;
	max-height: var(--navbar-height) !important;
	margin-top: 1px !important;
  	margin-bottom: calc(-1 * var(--navbar-height)) !important;
  	opacity: 1 !important;
  	transition: all 50ms linear 0s !important;
	z-index: 5 !important;
}


#urlbar-input-container {
        height: auto!important;
}

#urlbar[breakout] {
        top: calc((var(--navbar-height) - var(--urlbar-height)) / 2) !important;
}

/* Positions the url view to the bottom of your toolbar */
.urlbarView.megabar {
        top: calc((var(--navbar-height) - var(--urlbar-height)) / 2) !important;
        margin-block-start: 0 !important;
}

```
the 2 variables `--navbar-height` and `--urlbar-height` can be changed to what ever you like and the positions should be correct.

**Comment by A-Lamia** [comment]
So after some time i have figured out that the issue is the code is setting `#urlbar`'s internal variable `--urlbar-toolbar-height` to `1px` from `32px` (or what ever yours is set to.). 

The value of `--urlbar-toolbar-height` from what i can tell (could be wrong) is fetched from what ever the height of `#nav-bar` is on startup, in this case it gets set to 1px because of auto hide.

This is causing a `calc()` function on the `top` property in `#urlbar[breakout]` to calculate incorrectly giving us the positioning errors. 

```css
#nav-bar {
        --navbar-height: 32px;
        --urlbar-height: 26px;
 }

 #nav-bar:not([customizing="true"]):not([inFullscreen]){
	min-height: 1px !important;
	max-height: 0px !important;
	margin-top: 1px !important;
  	margin-bottom: -1px !important;
	transition: all 50ms linear 0s !important;
	z-index: -5 !important;
}

#navigator-toolbox:hover:not([inFullscreen]) :-moz-any(#nav-bar),
#navigator-toolbox:focus-within :-moz-any(#nav-bar) {
        min-height: var(--navbar-height) !important;
	max-height: var(--navbar-height) !important;
	margin-top: 1px !important;
  	margin-bottom: calc(-1 * var(--navbar-height)) !important;
  	opacity: 1 !important;
  	transition: all 50ms linear 0s !important;
	z-index: 5 !important;
}

/* Restores the variables original value. */
#urlbar.megabar {
        --urlbar-toolbar-height: var(--navbar-height) !important;
}


/* Positions the url view to the bottom of your toolbar and aligned with top border. */
.urlbarView.megabar {
        top: calc((var(--navbar-height) - var(--urlbar-height)) / 2) !important;
        margin-block-start: 0 !important;
}

```
the 2 variables `--navbar-height` and `--urlbar-height` can be changed to what ever you like and the positions should be correct.
