### ISSUE TITLE
Remove circle around back button (Nightly 57)

### ISSUE THREAD

**Issue by Skrity** [Timvde/UserChrome-Tweaks#9]
I dunno how to make PR so I figured I'll contribute this way.
Tested on W10/57.0a1 (2017-09-03) (64-bit). Not sure if complete, also probably hacky, so if someone can make it better you are welcome 👍 

```css
/* Remove circle, background, padding from backbutton */
:root:not([uidensity="compact"]) #back-button > .toolbarbutton-icon {
    background-color: unset !important;
    border: unset !important;
    padding: var(--toolbarbutton-inner-padding) !important;
    border-radius: var(--toolbarbutton-border-radius) !important; }
/* Hover and Active states to mimic other buttons */
:root:not([uidensity="compact"]) #back-button:hover:not([disabled]) > .toolbarbutton-icon {
    background-color: var(--toolbarbutton-hover-background) !important; }
:root:not([uidensity="compact"]) #back-button:active:not([disabled]) > .toolbarbutton-icon {
    background-color: var(--toolbarbutton-active-background) !important; }
/* Remove pre-padding */
:root:not([uidensity="compact"]) #back-button {
    /*padding-top: unset !important;
    padding-bottom: unset !important;   /* These two will screw nav-bar height (Nightly57)*/
    padding-inline-start: 3px !important; }
```
